SELECT TOP (1000) [id]
      ,[slaveId]
      ,[datStart]
      ,[datEnd]
      ,[duration]
      ,[channel1]
      ,[channel2]
      ,[channel3]
      ,[channel4]
      ,[error]
  FROM [WERMAWIN].[dbo].[slaveData]

